### ISSUE TITLE
Certifying Reporting period should add the Certified date to the previous reporting cycle immediately

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/arpa-reporter#125]
Actions:
- Reporting Periods > Certify the current reporting cycle

Expected result:
- Once it's finished certifying, the previous reporting cycle should fill in its "Certified At" Column

Actual result:
- the previous reporting cycle's "Certified At" Column stays blank until user refreshes the page

**Comment by ajhyndman** [comment]
@igor47 Is this fixed in #332 ?

**Comment by igor47** [comment]
yes, fixed in #332
