### ISSUE TITLE
exclude projects / recipients that have already been reported from new treasury reports

### ISSUE THREAD

**Issue by igor47** [usdigitalresponse/arpa-reporter#262]
we still need to get clarity on this.

both a feature request and possibly a bug (because possibly, reports that include previously-reported projects/recipients would be rejected by treasury at the bulk upload stage)

**Comment by igor47** [comment]
depends on #261 -- we'd use the same table

**Comment by jcomeau1** [comment]
I think the title is incorrect. We always need to report the projects which will evolve from period to period.

**Comment by jcomeau1** [comment]
Subrecipients already function correctly
