### ISSUE TITLE
Download Empty Template is bugged

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#286]
Returns a .json file

**Comment by igor47** [comment]
hmm, this works for me in my branch, we either fixed it, or it's a config setting on the render side.

**Comment by ajhyndman** [comment]
I think I found this one.  It looks like someone had previously uploaded a custom template for reporting period 1.  That file went into a random temp dir somewhere, so it's no longer accessible.

I cleared the filename from the DB entry, and downloading works again.
