### ISSUE TITLE
Unable to save edits to reporting periods

### ISSUE THREAD

**Issue by jmartin-oh** [usdigitalresponse/arpa-reporter#326]
I used to be able to update these fields (made changes from Quarterly # to align with reporting period end dates) but now am not able to! Thanks!
![Screenshot 2022-06-15 082649](https://user-images.githubusercontent.com/107556199/173826571-a1c85ed5-6804-4f2f-b68e-3b72c9f81a4c.png)

**Comment by igor47** [comment]
maybe #316 already fixes this? still waiting for review, ping @ajhyndman
