### ISSUE TITLE
Don't process subrecipients for invalid uploads

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#338]
Right now, we process subrecipients on upload.  This means that we will capture subrecipients from even invalid uploads.

I am not 100% sure if this is desirable or not, but we should probably check in with partners, and discuss the options.

**Comment by mattbroussard** [comment]
There is an `if (errors.length === 0)` check around the update (see [here](https://github.com/usdigitalresponse/arpa-reporter/blob/1728a883e8af4dced5a75d0d2b38610d67b2b047/src/server/services/validate-upload.js#L147)), but it's scoped only within `validateSubrecipientRecord` so if a given subrecipient record is considered valid but there are errors elsewhere in the spreadsheet, they will not be caught by this check.

**Comment by igor47** [comment]
fixed in #380

**Comment by igor47** [comment]
closed by #380
