### ISSUE TITLE
Viewing a reporting period other than CY22Q3 returns "'This reporting period is cloesd"

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/arpa-reporter#353]
Not able to upload files to a previous or (dummy) future quarter. I would like to do so, to illustrate to our partners next Monday the benefits of the audit report (comparison of key fields across quarters). 

Assuming this bug is resolved I'm also not sure whether the audit report will pull submissions across reporting quarters.

**Comment by igor47** [comment]
this is not a bug, it's by design. you'll have to close the reporting period to begin uploading files for the next reporting period.
