### ISSUE TITLE
Add way to populate previous reporting cycles by ingesting previously reported Treasury data

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/arpa-reporter#355]
A future-looking feature request:

As we bring on more partners, they will have already reported some data to the U.S. Treasury for previous cycles. They'll want to have all their reporting information stored in one place, to easily populate our tool with their previous reporting data. 

One way to do this that would be easy for users is if we can ingest the formats exported from the Treasury portal that summarizes previously uploaded reporting data.

**Comment by jcomeau1** [comment]
Within the Portal, you can "download CSV" for your project data. It would be helpful to be able to ingest this into Render.
