### ISSUE TITLE
Add Mindy's email as admin user to knex seeds

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#367]
Add a fourth email address to the default admin users in our database seeds.

**Comment by mhuang-usdr** [comment]
My email is mhuang@usdigitalresponse.org

**Comment by igor47** [comment]
adding truman -- might as well add yourself there, too. you just did this in your dev env.

**Comment by trumanc** [comment]
Completed this in https://github.com/usdigitalresponse/arpa-reporter/pull/390
