### ISSUE TITLE
Strange UI for a reporting period, UI returns to normal after a while

### ISSUE THREAD

**Issue by mindyatwork** [usdigitalresponse/arpa-reporter#376]
Reported by a partner.

In partner meeting today, one reported an issue that sounded similar to usdigitalresponse/usdr-gost#388 - they had funky UI popping up for one reporting period, and after a while and lots of refreshing it eventually went away.

**Comment by igor47** [comment]
what does "funky" mean? what does "for one reporting period" mean? what page was being refreshed?

**Comment by ajhyndman** [comment]
I'm pretty sure this is a browser caching issue.  JS files _should_ be hashed based on content though, so I'm not sure how it happens!  😬

**Comment by ajhyndman** [comment]
I can no longer reproduce this.  It looks like it has resolved itself.  👍
