### ISSUE TITLE
upload creation broken

### ISSUE THREAD

**Issue by igor47** [usdigitalresponse/arpa-reporter#379]
bug has to do with references to `upload.id` here:
https://github.com/usdigitalresponse/arpa-reporter/blob/46e515f2c6bead69dfe9bfb4c1ffda6b3ce884e7/src/views/NewUpload.vue#L87

**Comment by ajhyndman** [comment]
I can't repro.  What's the symptom for you?

**Comment by igor47** [comment]
nvm, i was misreading the code
