### ISSUE TITLE
Date mismatch

### ISSUE THREAD

**Issue by jmartin-oh** [usdigitalresponse/arpa-reporter#381]
Low priority at this time as there are not extensive date validations. :)

The Start and End dates do not match when comparing the Reporting Period "home" to each specific period (seen when editing). Even if if I edit to change it, it reverts back. 

![image](https://user-images.githubusercontent.com/107556199/176753251-75afea20-7d69-47d6-b1e5-e06790522d6c.png)

![image](https://user-images.githubusercontent.com/107556199/176753261-1cb798ca-e5d7-4d62-80b2-c9b77ebd1a96.png)

**Comment by ajhyndman** [comment]
See also: https://usdigitalresponse.slack.com/archives/C031R1Y49KL/p1657556392288429
