### ISSUE TITLE
Update input template with version newer than July 1st

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#393]
- [x] Joe to make changes to input template
- [ ] Update file in repository
- [ ] Regenerate validation rules

**Comment by jcomeau1** [comment]
I have released v20220705 of the input template. There are extensive changes to EC 5. You can find it on Google Drive: https://drive.google.com/drive/folders/1HCRiHQUrgS2EIZrWmikngma8sKo5pSMS?usp=sharing

I've also attached a Word doc with all of the updates to this issue
[Input Template Updates v20220705.docx](https://github.com/usdigitalresponse/arpa-reporter/files/9051292/Input.Template.Updates.v20220705.docx)

And in the hope that I can make your lives a little easier, of all the output templates, four of them had meaningful changes (beyond the Cancellation Explanation field, which affects all output templates). I have made a few comments to the output templates directly which may help make the input template changes more relatable.
[project519521BulkUpload.xlsx](https://github.com/usdigitalresponse/arpa-reporter/files/9051314/project519521BulkUpload.xlsx)
[projectBaselineBulkUploadTemplate.xlsx](https://github.com/usdigitalresponse/arpa-reporter/files/9051315/projectBaselineBulkUploadTemplate.xlsx)
[subawardBulkUpload.xlsx](https://github.com/usdigitalresponse/arpa-reporter/files/9051316/subawardBulkUpload.xlsx)
[subRecipientBulkUpload.xlsx](https://github.com/usdigitalresponse/arpa-reporter/files/9051317/subRecipientBulkUpload.xlsx)
.

**Comment by jcomeau1** [comment]
I have made a few small updates to the input template based on #399. I've updated Google Drive (still v20220705) and I've attached a revised Word doc with all of the changes.
https://drive.google.com/drive/folders/1HCRiHQUrgS2EIZrWmikngma8sKo5pSMS?usp=sharing

[Input Template Updates v20220705.docx](https://github.com/usdigitalresponse/arpa-reporter/files/9055760/Input.Template.Updates.v20220705.docx)
