### ISSUE TITLE
[Partner submission] One of our agency users is getting the following error: 	Error	Record EC code 2.16 (Long-term Housing Security: Services for Unhoused Persons) does not match any known EC code

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#419]
Link to submission is here:

https://ri-arpa-reporter-web.onrender.com/uploads/6c277d9a-06fd-48d8-b24c-579253abf321
https://www.jotform.com/uploads/grants.dev/212695501572052/5334437648218682894/prep1.PNG

**Comment by jmartin-oh** [comment]
I am getting a similar error for 5.12
![image](https://user-images.githubusercontent.com/107556199/178516138-0ae26ccc-df87-4670-8bda-5358572bf85b.png)

**Comment by jcomeau1** [comment]
Not sure what's happening with these codes. They do appear to be correct based on the list on the Logic sheet. Unfortunately, Ozzie's image didn't come through.

**Comment by jmartin-oh** [comment]
For 5.12 there is a comma in the User Guide wording - I did try to add that manually just in case, but that didn't work either! There is not a comma in the Treasury's template, but thought I might give it try if we had something older in the code!

Jessica Martin, CIA, CGAP
Financial Manager
Ohio Grants Partnership

**Comment by trumanc** [comment]
Is this EC code case sensitive?
I'm seeing here (https://github.com/usdigitalresponse/arpa-reporter/blob/staging/src/server/lib/arpa-ec-codes.js#L31) that we expect `Unhoused [p]ersons` to be lower case, but Ozzie's screenshot for code 2.16 is capitalized.

For code 5.12 in the first screenshot, the name is significantly different: https://github.com/usdigitalresponse/arpa-reporter/blob/staging/src/server/lib/arpa-ec-codes.js#L71

**Comment by trumanc** [comment]
I can fix those. Should I check all the other EC codes for accuracy? What should I treat as the source-of-truth for what these names should be?

**Comment by jmartin-oh** [comment]
Thank you!!! I think the bulk upload templates themselves, what is listed in the Sub_Category__C Column Notes as options. 

I just tried testing a bulk upload using what the User Guide indicates is the EC Name and I got errors.

**Comment by trumanc** [comment]
I've confirmed I've found at least one other outdated name (2.25) so I'm going to carefully go through all templates

**Comment by jcomeau1** [comment]
Sorry, I'm late to the game. All trailing spaces should be removed.

Truman, you should be able to rely on what's in the Input Template on the Logic sheet.

**Comment by trumanc** [comment]
I've now compared the values in the code against both the output templates that @jmartin-oh recommended, and the input template that @jcomeau1 recommended. There are two EC codes where the don't match up, and I need some guidance on which I should use. Differences are contained within the `{ }`

`EC 1.9: 1.9 COVID{-}19 Assistance to Non-Profits`
The output templates includes a `-` between `COVID` and `19`, but the guidance doc (page 99), input template, and current code are all missing the `-`.

and

`2.34-{Assistance to Non-Profits }Assistance to Impacted Nonprofit Organizations (Impacted or Disproportionately Impacted)`
The guidance doc (page 101) and the output template have both removed the stutter-start to the sentence, but the worksheet and previous code both include it.

It would be great to understand which of those options are more correct, probably by starting with understanding if the dev portal will reject either of them.

**Comment by jcomeau1** [comment]
For 1.9, the portal has (looks good):
![1_9](https://user-images.githubusercontent.com/78866741/178621230-e862a511-43ee-4af5-afae-82e09be12259.png)

and for 2.34 (an issue within the input template):
![2_34](https://user-images.githubusercontent.com/78866741/178621336-a9b62d78-7c16-4fbd-9339-4567d1a3acb5.png)

**Comment by jcomeau1** [comment]
I have a running list of updates for the Input Template. I think the best way to handle 2.34 (and others if they exist) is to have the agencies send their templates to the admins. The admins can then adjust the EC value and upload it.

**Comment by trumanc** [comment]
I'll update the code so that it expects the text seen in the portal, and if there are mismatches it will still succeed, with a warning, mentioning that the EC code has changed (showing the new value) and may need to be updated before the upload will succeed

**Comment by trumanc** [comment]
The quickest fix is to replace the current text with "Drinking water: Transmission & distribution: lead remediation".
Once the deploy is out it will no longer block the upload regardless of the name, so we're trying to get that out soon
