### ISSUE TITLE
[Partner submission] SFRF Audit Report - Adopted Budget Duplicating 

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#446]
**Submitted Description:**
Some strangeness with the audit report - see photo attached.

Adopted Budget is doubled in the Audit Report
TCO is doubled as well.
TCE results in NaN
CPO results in NaN
CPE results in NaN

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5339793258217124044/error11.PNG

**Comment by ozzie-chung** [comment]
This only applied to one project - 10010 EC 1.8

**Comment by ajhyndman** [comment]
I think this is related to #453

**Comment by ajhyndman** [comment]
Should be fixed with #466
