### ISSUE TITLE
[Partner submission] [Data Validation] Ensure email address format is valid (email address prefix + @ symbol + email domain)

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#455]
**Submitted Description:**
UST Portal rejected an upload for the email address b/c someone entered “James Comer jcomer@rihousing.com” - would be a nice-to-have feature to ensure entries follow a valid email address format ((email address prefix + @ symbol + email domain) either in Render or Excel

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5341677518212551069/Capture12.PNG

**Comment by ozzie-chung** [comment]
This submissions can be deleted, it's a duplicate. I must've submitted the same request twice.
