### ISSUE TITLE
[Partner submission] [Data Validation] Data Length Validation for UEI/TIN (in addition to data type validation, which already exists)

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#456]
**Submitted Description:**
Some agencies are submitting UEIs that are not 12 digits, or TINs that are not 9 digits. 

The UST Portal kicks back an error; would be nice if the agencies were forced to address these via data validation prior to our test upload in UST portal.

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5341687838215378611/Capture13.PNG

**Comment by ozzie-chung** [comment]
Did some more digging for this one after I submitted...the TIN starts with a 0, and entering the full TIN with the 0 into the Excel form removes the 0 (field treated as a number).

**Comment by mindyatwork** [comment]
Closing as obsolete.
