### ISSUE TITLE
[Partner submission] [Portal Bug] UST user guide does NOT say EC 2.35 requires evidence-based

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#467]
**Submitted Description:**
Here's what the user guide says:

For the table below, the following legend applies.
*[The asterisk] Denotes areas where recipients must identify the amount of the total funds that are allocated to evidence-based interventions (see Use of Evidence section above for details). 

Clearly the attached screenshot (capture15) does not have an asterisk.

And rightfully so the USDR workbook does not have questions pertaining to evidnce-based project spend or whether program evaluations will be conducted.

However the portal has it / requires it (capture16).

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5342959038218386574/Capture16.PNG
https://www.jotform.com/uploads/grants.dev/212695501572052/5342959038218386574/capture15.PNG

**Comment by jcomeau1** [comment]
That's kind of funny. The guidance of the field (col AB) explicitly states, "If aid is provided to industries other than travel, tourism, and hospitality (EC 2.36), please describe..." whereas 2.35 actually is Aid to Tourism, Travel or Hospitality.

The workaround, if UST doesn't address this is to go to the Logic sheet and add an "x" to the AB column (row 2) for 2.35
