### ISSUE TITLE
Remove leading and trailing whitespace from all fields in treasury export

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#476]
As discussed in client meeting on Jul 25th, remove leading and trailing whitespace from all text fields in treasury exports.

**Comment by trumanc** [comment]
This issue was fixed in https://github.com/usdigitalresponse/arpa-reporter/pull/472

Any user string inputs will now have leading/trailing whitespace removed before writing those values out to any export files.
