### ISSUE TITLE
Generate Audit Report is too slow

### ISSUE THREAD

**Issue by ajhyndman** [usdigitalresponse/arpa-reporter#487]
Can we optimize the processing of this report?

**Comment by mattbroussard** [comment]
#497 is an optimization that helps this.

If we get to a point where audit report generation is complicated enough that optimizations like that don't get us below the request timeout (do we know what that limit is?) we could consider decoupling report generation from request lifetime -- e.g. the client sends one request to start generation, which kicks off the process and returns immediately; then the client polls in separate requests to find out when the job is done.

**Comment by mindyatwork** [comment]
Closing for now, will ask partners to resubmit issue if it's still too slow.
