### ISSUE TITLE
[Partner submission] Certain Fields Prompts Users to Enter the USDR password (or returns a Runtime error)

### ISSUE THREAD

**Issue by usdr-grants** [usdigitalresponse/arpa-reporter#519]
**Submitted Description:**
In the sample screenshot, I selected EC 2.28 and navigated to the 'Subrecipient' tab and attempted to enter a value in 'Entity Type'.

**(Optional) Uploaded file - click to download:**
https://www.jotform.com/uploads/grants.dev/212695501572052/5384764634524605709/px1.PNG

**Comment by jcomeau1** [comment]
In addition to Subrecipient: Entity Type, this also affected EC 4 - Premium Pay: Sectors Designated as Essential Critical Infrastructure. Both have been addressed and added to v20220902.
