### ISSUE TITLE
Export in ARPA-required formats

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/arpa-reporter#57]
Expected export templates are here: https://drive.google.com/drive/u/0/folders/1Z-AS0acaY_HdO5Y4rbFNwBTOuxeMTsjm

Mapping from project expenditure category to templates starts on page 62: https://drive.google.com/file/d/1rNgA8bAUhUThJfzjKPJzKzYggOFp6dtt/view?usp=sharing

Supported templates:

- [x] expendituresGT50000BulkUpload.xlsx
- [x] expendituresLT50000BulkUpload.xlsx
- [x] paymentsIndividualsLT50000BulkUpload.xlsx
- [x] project18_229233BulkUploads.xlsx
- [x] project19_234BulkUploads.xlsx
- [x] project2128BulkUploads.xlsx
- [x] project214_224227BulkUploads.xlsx
- [x] project236BulkUploads.xlsx  
- [x] project31BulkUpload.xlsx
- [x] project32BulkUpload.xlsx
- [x] project4142BulkUpload.xlsx
- [x] project51518BulkUpload.xlsx
- [x] project519521BulkUpload.xlsx
- [x] projectBaselineBulkUpload.xlsx
- [x] subRecipientBulkUpload.xlsx
- [x] subawardBulkUpload.xlsx

**Comment by ajhyndman** [comment]
I'm adding a checklist here to track progress!

- [x] expendituresGT50000BulkUpload.xlsx        
- [ ] expendituresLT50000BulkUpload.xlsx        
- [ ] paymentsIndividualsLT50000BulkUpload.xlsx 
- [ ] project18_229233BulkUploads.xlsx          
- [ ] project19_234BulkUploads.xlsx             
- [ ] project2128BulkUploads.xlsx               
- [ ] project214_224227BulkUploads.xlsx         
- [ ] project236BulkUploads.xlsx                
- [ ] project31BulkUpload.xlsx
- [ ] project32BulkUpload.xlsx
- [ ] project4142BulkUpload.xlsx
- [ ] project51518BulkUpload.xlsx
- [ ] project519521BulkUpload.xlsx
- [x] projectBaselineBulkUpload.xlsx
- [ ] subRecipientBulkUpload.xlsx
- [x] subawardBulkUpload.xlsx

**Comment by ajhyndman** [comment]
It looks like EC code to template mapping starts on page 55 as of today (2022-05-24).
