### ISSUE TITLE
set/maybe upgrade the nodejs version

### ISSUE THREAD

**Issue by igor47** [usdigitalresponse/arpa-reporter#64]
the node version to use with the project is unclear. we should add guidance about that to the readme and maybe a file used by nodenv to make it more clear. we might want to upgrade the nodejs version. we should coordinate the upgrade with the various render instances that run this code -- there might be render configuration that specifies the version.

**Comment by cmroberts** [comment]
Just upgraded a few things over in https://github.com/usdigitalresponse/usdr-gost/pull/32 to make that project compatible with node 16. Sounds like this one is on that version too. 

Here are the options for setting the node version on render: https://render.com/docs/node-version . I like option 2: 
```
Add a file called .node-version at the root of your repo containing a single line specifying the version.
```

**Comment by mhuang-usdr** [comment]
From Christina: Don't upgrade after node 14, Vue 2.0 is only compatible up to 14
