### ISSUE TITLE
Update language from CARES to ARPA

### ISSUE THREAD

**Issue by mhuang-usdr** [usdigitalresponse/arpa-reporter#75]
- [ ] Email language
- [ ] DOM<title> 
- [ ] Add "ARPA Reporter" to the page title, so "Rhode Island" becomes "Rhode Island - ARPA reporting"

<img width="557" alt="image" src="https://user-images.githubusercontent.com/91221265/153465457-31ba2b29-f274-4872-b82e-e62f7a97f38b.png">

**Comment by ajhyndman** [comment]
This should be fixed in #58 !
